version: '3.8'

networks:
  bazar_api_network:
    driver: bridge

services:

  db:
    image: postgres:13.4
    networks:
      - bazar_api_network
    container_name: db_postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bazar_db