version: '3.8'

services:

  db:
    image: postgres
    container_name: db_postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bazar_db